# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            wrtsprt
tagline:          wrtsprt sein blog.
url:              http://blog.wrtsprt.me
baseurl:          /
description:      '/* no comment */'
paginate:         5
author:
  name:           Raphael Doehring
  url:            https://twitter.com/wrtsprt

# Archives
jekyll-archives:
  enabled:
    - year
  layouts:
    year: yearly

gems:
  - jekyll-archives
